// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modulo.Rendiciones.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modulo.Rendiciones.Migrations.Postgres.Migrations
{
    [DbContext(typeof(RendicionesDbContext))]
    [Migration("20260812014905_AddRendicionesSettingsAndReminderLog")]
    partial class AddRendicionesSettingsAndReminderLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulo.Rendiciones.Models.DocumentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AppliesTax")
                        .HasColumnType("boolean")
                        .HasColumnName("applies_tax");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_percentage");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_document_types_company_id");

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseApprovalGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("expense_approval_groups", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseApprovalGroupLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExpenseApprovalGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_approval_group_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseApprovalGroupId", "Level")
                        .IsUnique()
                        .HasDatabaseName("uq_expense_approval_group_levels_group_id_level");

                    b.ToTable("expense_approval_group_levels", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseApprovalGroupMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExpenseApprovalGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_approval_group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseApprovalGroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_expense_approval_group_members_group_id_user_id");

                    b.ToTable("expense_approval_group_members", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseFund", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_center_code");

                    b.Property<string>("CostCenterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cost_center_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset?>("SettlementDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settlement_due_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_expense_funds_company_id");

                    b.ToTable("expense_funds", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpensePolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<long>("ExpenseTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_type_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocking");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_amount");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("expense_policies", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("expense_receipts", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_center_code");

                    b.Property<string>("CostCenterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cost_center_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentLevel")
                        .HasColumnType("integer")
                        .HasColumnName("current_level");

                    b.Property<long?>("ExpenseApprovalGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_approval_group_id");

                    b.Property<long?>("ExpenseFundId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_fund_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_expense_reports_company_id");

                    b.HasIndex("ExpenseApprovalGroupId");

                    b.HasIndex("ExpenseFundId");

                    b.ToTable("expense_reports", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseReportAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<long>("ExpenseReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_report_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseReportId");

                    b.ToTable("expense_report_actions", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseReportLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("AppliedRatePerKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("applied_rate_per_km");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expense_date");

                    b.Property<string>("Destination")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("destination");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("distance_km");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<long?>("DocumentTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_type_id");

                    b.Property<long?>("ExpenseReceiptId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_receipt_id");

                    b.Property<long?>("ExpenseReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_report_id");

                    b.Property<long?>("ExpenseTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("expense_type_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Origin")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("origin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("SupplierTaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("supplier_tax_id");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_expense_report_lines_company_id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ExpenseReceiptId");

                    b.HasIndex("ExpenseReportId");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("expense_report_lines", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMileage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mileage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("RatePerKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rate_per_km");

                    b.Property<string>("SapGlAccount")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sap_gl_account");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_expense_types_company_id");

                    b.ToTable("expense_types", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExternalServiceProvider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key_encrypted");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MonthlyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ServiceType", "Priority")
                        .HasDatabaseName("ix_external_service_providers_company_service_priority");

                    b.ToTable("external_service_providers", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExternalServiceUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<long>("ProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_id");

                    b.Property<int>("UsedUnits")
                        .HasColumnType("integer")
                        .HasColumnName("used_units");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("uq_external_service_usages_provider_year_month");

                    b.ToTable("external_service_usages", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ReminderLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("SentDate")
                        .HasColumnType("date")
                        .HasColumnName("sent_date");

                    b.HasKey("Id");

                    b.HasIndex("SentDate")
                        .IsUnique()
                        .HasDatabaseName("uq_rendiciones_reminder_log_sent_date");

                    b.ToTable("rendiciones_reminder_log", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.RendicionesSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_enabled");

                    b.Property<TimeOnly>("ReminderHour")
                        .HasColumnType("time without time zone")
                        .HasColumnName("reminder_hour");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("rendiciones_settings", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.UserCostCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CostCenterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_center_code");

                    b.Property<string>("CostCenterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cost_center_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "UserId")
                        .HasDatabaseName("ix_user_cost_centers_company_id_user_id");

                    b.ToTable("user_cost_centers", (string)null);
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseApprovalGroupLevel", b =>
                {
                    b.HasOne("Modulo.Rendiciones.Models.ExpenseApprovalGroup", "ExpenseApprovalGroup")
                        .WithMany()
                        .HasForeignKey("ExpenseApprovalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_approval_group_levels_expense_approval_groups");

                    b.Navigation("ExpenseApprovalGroup");
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseApprovalGroupMember", b =>
                {
                    b.HasOne("Modulo.Rendiciones.Models.ExpenseApprovalGroup", "ExpenseApprovalGroup")
                        .WithMany()
                        .HasForeignKey("ExpenseApprovalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_approval_group_members_expense_approval_groups");

                    b.Navigation("ExpenseApprovalGroup");
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpensePolicy", b =>
                {
                    b.HasOne("Modulo.Rendiciones.Models.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_policies_expense_types");

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseReport", b =>
                {
                    b.HasOne("Modulo.Rendiciones.Models.ExpenseApprovalGroup", null)
                        .WithMany()
                        .HasForeignKey("ExpenseApprovalGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expense_reports_expense_approval_groups");

                    b.HasOne("Modulo.Rendiciones.Models.ExpenseFund", null)
                        .WithMany()
                        .HasForeignKey("ExpenseFundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expense_reports_expense_funds");
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseReportAction", b =>
                {
                    b.HasOne("Modulo.Rendiciones.Models.ExpenseReport", null)
                        .WithMany()
                        .HasForeignKey("ExpenseReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_report_actions_expense_reports");
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseReportLine", b =>
                {
                    b.HasOne("Modulo.Rendiciones.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expense_report_lines_document_types");

                    b.HasOne("Modulo.Rendiciones.Models.ExpenseReceipt", "ExpenseReceipt")
                        .WithMany()
                        .HasForeignKey("ExpenseReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expense_report_lines_expense_receipts");

                    b.HasOne("Modulo.Rendiciones.Models.ExpenseReport", "ExpenseReport")
                        .WithMany("Lines")
                        .HasForeignKey("ExpenseReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expense_report_lines_expense_reports");

                    b.HasOne("Modulo.Rendiciones.Models.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expense_report_lines_expense_types");

                    b.Navigation("DocumentType");

                    b.Navigation("ExpenseReceipt");

                    b.Navigation("ExpenseReport");

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExternalServiceUsage", b =>
                {
                    b.HasOne("Modulo.Rendiciones.Models.ExternalServiceProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_service_usages_external_service_providers");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Modulo.Rendiciones.Models.ExpenseReport", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
