-- Puebla dbo.Maestro_Sucursal_Canal, que YA estaba diseñada y conectada (LEFT JOIN) dentro de
-- dbo.vw_VentaBaseDistribucion para corregir el canal real por sucursal en el prorrateo del motor
-- automático (sp_EjecutarDistribucionAutomatica). Estaba vacía, por eso la corrección nunca se aplicaba
-- (el ISNULL de la vista siempre caía al canal original digitado en SAP).
-- Misma fuente que Sql/Maestro_Sucursal.sql: Cuentas_dimensiones.txt provisto por el usuario el 2026-07-15.

DELETE FROM dbo.Maestro_Sucursal_Canal;

-- Nota: se excluyen a propósito 0100, 0200, 0301, 0400, 0600, 0700, 0800, 1200 y 1300 (códigos que no
-- deberían estar en el maestro), igual que en Sql/Maestro_Sucursal.sql, para que ambas tablas coincidan.
INSERT INTO dbo.Maestro_Sucursal_Canal (CodSucursal, NombreSucursal, CodCanal, NombreCanal, Activo, FechaCreacion, UsuarioCreacion) VALUES
('0101', 'CONV. MALL LA DEHESA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0102', 'CONV. PLAZA VESPUCIO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0103', 'CONV. PQUE. ARAUCO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0104', 'CONV. PLAZA OESTE', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0105', 'CONV. PLAZA TREBOL', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0106', 'CONV. ALTO LAS CONDES', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0107', 'CONV. COSTANERA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0108', 'CONV. MALL CONCEPCION', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0109', 'CONV. FLORIDA CENTER', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0110', 'CONV. ANTOFAGASTA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0111', 'CONV. LA SERENA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0112', 'CONV. MARINA ARAUCO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0113', 'CONV. MALL LOS DOMINICOS', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0114', 'CONV. MALL IMPERIO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0115', 'CONV. INDEPENDENCIA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0116', 'CONV. PUERTO MONTT', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0117', 'CONV. TEMUCO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0201', 'COLISEUM PLAZA OESTE', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0202', 'COLISEUM MAIPU', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0203', 'COLISEUM PLAZA ALAMEDA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0204', 'COLISEUM TEMUCO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0205', 'COLISEUM IQUIQUE', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0206', 'COLISEUM PLAZA NORTE', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0207', 'COLISEUM COQUIMBO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0208', 'COLISEUM ARICA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0209', 'COLIEUM OSORNO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0210', 'COLISEUM P.ARAUCO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0300', 'TIENDAS STEVE MADDEN', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0302', 'SM - COSTANERA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0303', 'SM - MALL LOS DOMINICOS', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0304', 'SM - MALL IMPERIO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0305', 'SM - MARINA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0306', 'SM VESPUCIO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0307', 'SM-PARQUE ARAUCO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0308', 'SM-ANTOGAGASTA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0401', 'COLEHAAN-CASA COSTANERA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0601', 'OUTLET MALL EASTON', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0602', 'OUTLET COLISEUM BUENAVENTURA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0603', 'OUTLET MALL VIVO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0604', 'OUTLET SM-CH BUENAVENTURA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0605', 'OUTLET COLISEUM ANTOFAGASTA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0606', 'CFS SAN PEDRO DE LA PAZ', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0607', 'OUTLET COLISEUM ALAMEDA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0608', 'OUTLET CONVERSE BUENAVENTURA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0609', 'OUTLET COLISEUM BIOBIO', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0610', 'OUTLET SM BUENAVENTURA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('1301', 'FILA COSTANERA', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('1302', 'FILA FLORIDA CENTER', 'TPR', 'Tiendas Propias', 1, GETDATE(), 'sistema'),
('0701', 'COLISEUM STORE', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0702', 'STEVE MADDEN', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0703', 'ECOMMERCE CONVERSE-CL', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0704', 'ECOMMERCE FILA-CL', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0705', 'ECOMMERCE UMBRO-CL', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0801', 'DAFITI', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0802', 'MERCADO LIBRE', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0803', 'MERCADOLIBRE FULL', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0804', 'MKP FALABELLA', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0806', 'MKP RIPLEY', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0807', 'MKP FALABELLA FULL', 'ECM', 'Ecommerce', 1, GETDATE(), 'sistema'),
('0900', 'MULTITIENDAS', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('0901', 'Falabella', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('0902', 'Ripley', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('0903', 'Paris', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('0904', 'Hites', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('0905', 'La Polar', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('0906', 'Corona', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1001', 'Patuelli y Cia.', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1002', 'Belsport', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1003', 'Block', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1004', 'Bata', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1005', 'Tricot', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1006', 'Antonio Patuelli', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1007', 'Sparta', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1008', 'Tactic', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1009', 'Big Foot', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1010', 'International Sport', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1011', 'Hit SA', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1012', 'Otros Especialistas', 'MAY', 'Mayoristas', 1, GETDATE(), 'sistema'),
('1102', 'Clientes Regionales', 'REG', 'Regiones', 1, GETDATE(), 'sistema'),
('1201', 'OTRAS VENTAS', 'OTROS', 'Otros', 1, GETDATE(), 'sistema'),
('1202', 'VENTA MOVIL', 'OTROS', 'Otros', 1, GETDATE(), 'sistema'),
('IND4', 'Central', 'OTROS', 'Otros', 1, GETDATE(), 'sistema');
