-- Maestro_Sucursal: jerarquía real y fija Sucursal -> Canal -> Centro de costo.
-- Fuente de verdad mencionada en CLAUDE.md sección 6.1 (pendiente #1), cargada desde
-- Cuentas_dimensiones.txt provisto por el usuario el 2026-07-15.
-- Ejecutar manualmente contra CLDEPORFIN (no se aplica vía EF Migrations en este proyecto).

IF OBJECT_ID('dbo.Maestro_Sucursal', 'U') IS NOT NULL
    DROP TABLE dbo.Maestro_Sucursal;

CREATE TABLE dbo.Maestro_Sucursal (
    CodSucursal    VARCHAR(10)  NOT NULL PRIMARY KEY,
    Sucursal       VARCHAR(100) NOT NULL,
    CodCanal       VARCHAR(10)  NOT NULL,
    Canal          VARCHAR(100) NOT NULL,
    CodCentroCosto VARCHAR(10)  NOT NULL,
    CentroCosto    VARCHAR(100) NOT NULL
);

INSERT INTO dbo.Maestro_Sucursal (CodSucursal, Sucursal, CodCanal, Canal, CodCentroCosto, CentroCosto) VALUES
('0101', 'CONV. MALL LA DEHESA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0102', 'CONV. PLAZA VESPUCIO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0103', 'CONV. PQUE. ARAUCO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0104', 'CONV. PLAZA OESTE', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0105', 'CONV. PLAZA TREBOL', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0106', 'CONV. ALTO LAS CONDES', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0107', 'CONV. COSTANERA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0108', 'CONV. MALL CONCEPCION', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0109', 'CONV. FLORIDA CENTER', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0110', 'CONV. ANTOFAGASTA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0111', 'CONV. LA SERENA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0112', 'CONV. MARINA ARAUCO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0113', 'CONV. MALL LOS DOMINICOS', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0114', 'CONV. MALL IMPERIO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0115', 'CONV. INDEPENDENCIA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0116', 'CONV. PUERTO MONTT', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0117', 'CONV. TEMUCO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0201', 'COLISEUM PLAZA OESTE', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0202', 'COLISEUM MAIPU', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0203', 'COLISEUM PLAZA ALAMEDA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0204', 'COLISEUM TEMUCO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0205', 'COLISEUM IQUIQUE', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0206', 'COLISEUM PLAZA NORTE', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0207', 'COLISEUM COQUIMBO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0208', 'COLISEUM ARICA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0209', 'COLIEUM OSORNO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0210', 'COLISEUM P.ARAUCO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0300', 'TIENDAS STEVE MADDEN', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0302', 'SM - COSTANERA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0303', 'SM - MALL LOS DOMINICOS', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0304', 'SM - MALL IMPERIO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0305', 'SM - MARINA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0306', 'SM VESPUCIO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0307', 'SM-PARQUE ARAUCO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0308', 'SM-ANTOGAGASTA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0401', 'COLEHAAN-CASA COSTANERA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0601', 'OUTLET MALL EASTON', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0602', 'OUTLET COLISEUM BUENAVENTURA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0603', 'OUTLET MALL VIVO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0604', 'OUTLET SM-CH BUENAVENTURA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0605', 'OUTLET COLISEUM ANTOFAGASTA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0606', 'CFS SAN PEDRO DE LA PAZ', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0607', 'OUTLET COLISEUM ALAMEDA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0608', 'OUTLET CONVERSE BUENAVENTURA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0609', 'OUTLET COLISEUM BIOBIO', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0610', 'OUTLET SM BUENAVENTURA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('1301', 'FILA COSTANERA', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('1302', 'FILA FLORIDA CENTER', 'TPR', 'Tiendas Propias', '2501', 'Omnicanal Retail'),
('0701', 'COLISEUM STORE', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0702', 'STEVE MADDEN', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0703', 'ECOMMERCE CONVERSE-CL', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0704', 'ECOMMERCE FILA-CL', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0705', 'ECOMMERCE UMBRO-CL', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0801', 'DAFITI', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0802', 'MERCADO LIBRE', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0803', 'MERCADOLIBRE FULL', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0804', 'MKP FALABELLA', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0806', 'MKP RIPLEY', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0807', 'MKP FALABELLA FULL', 'ECM', 'Ecommerce', '2504', 'Omnicanal Ecommerce'),
('0900', 'MULTITIENDAS', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('0901', 'Falabella', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('0902', 'Ripley', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('0903', 'Paris', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('0904', 'Hites', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('0905', 'La Polar', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('0906', 'Corona', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1001', 'Patuelli y Cia.', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1002', 'Belsport', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1003', 'Block', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1004', 'Bata', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1005', 'Tricot', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1006', 'Antonio Patuelli', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1007', 'Sparta', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1008', 'Tactic', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1009', 'Big Foot', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1010', 'International Sport', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1011', 'Hit SA', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1012', 'Otros Especialistas', 'MAY', 'Mayoristas', '2301', 'Ventas Mayoristas Kam'),
('1102', 'Clientes Regionales', 'REG', 'Regiones', '2303', 'Ventas Regionales'),
('1201', 'OTRAS VENTAS', 'OTROS', 'Otros', '9999', 'Indirectos Central'),
('1202', 'VENTA MOVIL', 'OTROS', 'Otros', '9999', 'Indirectos Central'),
('IND4', 'Central', 'OTROS', 'Otros', '9999', 'Indirectos Central');
