// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modulo.AuditoriaInventario.Data;

#nullable disable

namespace Modulo.AuditoriaInventario.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(AuditoriaInventarioDbContext))]
    [Migration("20260929160135_AddCaptureSettings")]
    partial class AddCaptureSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch_code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SapCompanyCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sap_company_code");

                    b.Property<string>("SapWarehouseCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sap_warehouse_code");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "BranchCode")
                        .IsUnique()
                        .HasDatabaseName("uq_branches_company_id_branch_code");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.CaptureAuthToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CaptureUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("capture_user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("CaptureUserId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("uq_capture_auth_tokens_token");

                    b.ToTable("capture_auth_tokens", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.CaptureSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowEan13")
                        .HasColumnType("bit")
                        .HasColumnName("allow_ean13");

                    b.Property<bool>("AllowEan8")
                        .HasColumnType("bit")
                        .HasColumnName("allow_ean8");

                    b.Property<bool>("AllowUpcA")
                        .HasColumnType("bit")
                        .HasColumnName("allow_upca");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("uq_capture_settings_company_id");

                    b.ToTable("capture_settings", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.CaptureUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Username")
                        .IsUnique()
                        .HasDatabaseName("uq_capture_users_company_id_username");

                    b.ToTable("capture_users", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.FrozenInventoryLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("product_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Barcode")
                        .HasDatabaseName("ix_frozen_inventory_lines_snapshot_barcode");

                    b.ToTable("frozen_inventory_lines", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.FrozenInventorySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("file_name");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("inventory_number");

                    b.Property<DateTimeOffset>("LoadedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("loaded_at");

                    b.Property<Guid>("LoadedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId", "BranchId", "InventoryNumber")
                        .HasDatabaseName("ix_frozen_snapshots_company_branch_inventory_number");

                    b.ToTable("frozen_inventory_snapshots", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventoryAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approved_by_user_id");

                    b.Property<long>("DifferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("difference_id");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("proposed_at");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("proposed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DifferenceId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_adjustments_status");

                    b.ToTable("inventory_adjustments", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventoryCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("captured_at");

                    b.Property<long>("CapturedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("captured_by_user_id");

                    b.Property<bool?>("InMaster")
                        .HasColumnType("bit")
                        .HasColumnName("in_master");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("product_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<long>("SectorId")
                        .HasColumnType("bigint")
                        .HasColumnName("sector_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset?>("SyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("CapturedByUserId");

                    b.HasIndex("SectorId");

                    b.HasIndex("SessionId", "SectorId", "Barcode")
                        .HasDatabaseName("ix_inventory_captures_session_sector_barcode");

                    b.ToTable("inventory_captures", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventoryDifference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountDiff")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_diff");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("calculated_at");

                    b.Property<int>("CapturedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("captured_quantity");

                    b.Property<int>("FrozenQuantity")
                        .HasColumnType("int")
                        .HasColumnName("frozen_quantity");

                    b.Property<int>("QuantityDiff")
                        .HasColumnType("int")
                        .HasColumnName("quantity_diff");

                    b.Property<long?>("SectorId")
                        .HasColumnType("bigint")
                        .HasColumnName("sector_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_inventory_differences_session_id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("inventory_differences", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventorySector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_inventory_sectors_company_id");

                    b.ToTable("inventory_sectors", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventorySession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("inventory_number");

                    b.Property<DateTimeOffset?>("MasterSnapshotAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("master_snapshot_at");

                    b.Property<long>("ResponsibleUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<bool>("ValidateAgainstMaster")
                        .HasColumnType("bit")
                        .HasColumnName("validate_against_master");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("CompanyId", "BranchId", "Status")
                        .HasDatabaseName("ix_inventory_sessions_company_branch_status");

                    b.ToTable("inventory_sessions", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("brand");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("Line")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("line");

                    b.Property<DateTimeOffset>("LoadedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("loaded_at");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("product_code");

                    b.Property<string>("SapMaterialCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sap_material_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("uq_products_company_id_barcode");

                    b.HasIndex("CompanyId", "ProductCode")
                        .HasDatabaseName("ix_products_company_id_product_code");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.SapAdjustmentQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AdjustmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("adjustment_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("generated_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("SapCompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sap_company_code");

                    b.Property<string>("SapDocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sap_document_number");

                    b.Property<string>("SapMaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sap_material_code");

                    b.Property<string>("SapWarehouseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sap_warehouse_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sap_adjustment_queue_items_status");

                    b.ToTable("sap_adjustment_queue_items", (string)null);
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.CaptureAuthToken", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.CaptureUser", null)
                        .WithMany()
                        .HasForeignKey("CaptureUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capture_auth_tokens_capture_users");
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.FrozenInventoryLine", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.FrozenInventorySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_frozen_inventory_lines_frozen_inventory_snapshots");
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.FrozenInventorySnapshot", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_frozen_inventory_snapshots_branches");
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventoryAdjustment", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.InventoryDifference", null)
                        .WithMany()
                        .HasForeignKey("DifferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_adjustments_inventory_differences");
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventoryCapture", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.CaptureUser", null)
                        .WithMany()
                        .HasForeignKey("CapturedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_captures_capture_users");

                    b.HasOne("Modulo.AuditoriaInventario.Models.InventorySector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_captures_inventory_sectors");

                    b.HasOne("Modulo.AuditoriaInventario.Models.InventorySession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_captures_inventory_sessions");
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventoryDifference", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.InventorySession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_differences_inventory_sessions");

                    b.HasOne("Modulo.AuditoriaInventario.Models.FrozenInventorySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_differences_frozen_inventory_snapshots");
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventorySector", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_sectors_branches");
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.InventorySession", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_sessions_branches");

                    b.HasOne("Modulo.AuditoriaInventario.Models.CaptureUser", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_sessions_capture_users");
                });

            modelBuilder.Entity("Modulo.AuditoriaInventario.Models.SapAdjustmentQueueItem", b =>
                {
                    b.HasOne("Modulo.AuditoriaInventario.Models.InventoryAdjustment", null)
                        .WithMany()
                        .HasForeignKey("AdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sap_adjustment_queue_items_inventory_adjustments");
                });
#pragma warning restore 612, 618
        }
    }
}
