namespace Modulo.Wms.Models;

public enum WmsSlshStatus { Pendiente, ProcesadoSap, ErrorSap }

public class WmsOracleStageSlsh
{
    public long LineId { get; set; }
    public long ParentId { get; set; }
    public WmsSlshStatus Status { get; set; } = WmsSlshStatus.Pendiente;
    public string? ErrorMsg { get; set; }
    public int RetryCount { get; set; }
    public int? SapDocEntry { get; set; }
    public int? SapObject { get; set; }

    // Columnas de negocio (estándar "shipped_load" de Oracle WMS Cloud) — todas nullable,
    // nombres idénticos al DDL real (ya en snake_case, sin traducir).
    public string? DocumentVersion { get; set; }
    public string? OriginSystem { get; set; }
    public string? ClientEnvCode { get; set; }
    public string? ParentCompanyCode { get; set; }
    public string? Entity { get; set; }
    public string? TimeStamp { get; set; }
    public string? MessageId { get; set; }
    public string? facility_code { get; set; }
    public string? company_code { get; set; }
    public string? action_code { get; set; }
    public string? load_type { get; set; }
    public string? load_manifest_nbr { get; set; }
    public string? trailer_nbr { get; set; }
    public string? trailer_type { get; set; }
    public string? driver { get; set; }
    public string? seal_nbr { get; set; }
    public string? pro_nbr { get; set; }
    public string? route_nbr { get; set; }
    public string? freight_class { get; set; }
    public string? hdr_bol_nbr { get; set; }
    public string? total_nbr_of_oblpns { get; set; }
    public string? total_weight { get; set; }
    public string? total_volume { get; set; }
    public string? total_shipping_charge { get; set; }
    public string? ship_date { get; set; }
    public string? sched_delivery_date { get; set; }
    public string? carrier_code { get; set; }
    public string? externally_planned_load_nbr { get; set; }
    public string? ship_date_time { get; set; }
    public string? sched_delivery_date_time { get; set; }
    public string? line_nbr { get; set; }
    public string? seq_nbr { get; set; }
    public string? stop_shipment_nbr { get; set; }
    public string? stop_bol_nbr { get; set; }
    public string? stop_nbr_of_oblpns { get; set; }
    public string? stop_weight { get; set; }
    public string? stop_volume { get; set; }
    public string? stop_shipping_charge { get; set; }
    public string? shipto_facility_code { get; set; }
    public string? shipto_name { get; set; }
    public string? shipto_addr { get; set; }
    public string? shipto_addr2 { get; set; }
    public string? shipto_addr3 { get; set; }
    public string? shipto_city { get; set; }
    public string? shipto_state { get; set; }
    public string? shipto_zip { get; set; }
    public string? shipto_country { get; set; }
    public string? shipto_phone_nbr { get; set; }
    public string? shipto_email { get; set; }
    public string? shipto_contact { get; set; }
    public string? dest_facility_code { get; set; }
    public string? cust_name { get; set; }
    public string? cust_addr { get; set; }
    public string? cust_addr2 { get; set; }
    public string? cust_addr3 { get; set; }
    public string? cust_city { get; set; }
    public string? cust_state { get; set; }
    public string? cust_zip { get; set; }
    public string? cust_country { get; set; }
    public string? cust_phone_nbr { get; set; }
    public string? cust_email { get; set; }
    public string? cust_contact { get; set; }
    public string? cust_nbr { get; set; }
    public string? order_nbr { get; set; }
    public string? ord_date { get; set; }
    public string? exp_date { get; set; }
    public string? req_ship_date { get; set; }
    public string? start_ship_date { get; set; }
    public string? stop_ship_date { get; set; }
    public string? host_allocation_nbr { get; set; }
    public string? customer_po_nbr { get; set; }
    public string? sales_order_nbr { get; set; }
    public string? sales_channel { get; set; }
    public string? dest_dept_nbr { get; set; }
    public string? order_hdr_cust_field_1 { get; set; }
    public string? order_hdr_cust_field_2 { get; set; }
    public string? order_hdr_cust_field_3 { get; set; }
    public string? order_hdr_cust_field_4 { get; set; }
    public string? order_hdr_cust_field_5 { get; set; }
    public string? order_seq_nbr { get; set; }
    public string? order_dtl_cust_field_1 { get; set; }
    public string? order_dtl_cust_field_2 { get; set; }
    public string? order_dtl_cust_field_3 { get; set; }
    public string? order_dtl_cust_field_4 { get; set; }
    public string? order_dtl_cust_field_5 { get; set; }
    public string? ob_lpn_nbr { get; set; }
    public string? item_alternate_code { get; set; }
    public string? item_part_a { get; set; }
    public string? item_part_b { get; set; }
    public string? item_part_c { get; set; }
    public string? item_part_d { get; set; }
    public string? item_part_e { get; set; }
    public string? item_part_f { get; set; }
    public string? pre_pack_code { get; set; }
    public string? pre_pack_ratio { get; set; }
    public string? pre_pack_ratio_seq { get; set; }
    public string? pre_pack_total_units { get; set; }
    public string? invn_attr_a { get; set; }
    public string? invn_attr_b { get; set; }
    public string? invn_attr_c { get; set; }
    public string? hazmat { get; set; }
    public string? shipped_uom { get; set; }
    public string? shipped_qty { get; set; }
    public string? pallet_nbr { get; set; }
    public string? dest_company_code { get; set; }
    public string? batch_nbr { get; set; }
    public string? expiry_date { get; set; }
    public string? tracking_nbr { get; set; }
    public string? master_tracking_nbr { get; set; }
    public string? package_type { get; set; }
    public string? payment_method { get; set; }
    public string? carrier_account_nbr { get; set; }
    public string? ship_via_code { get; set; }
    public string? ob_lpn_weight { get; set; }
    public string? ob_lpn_volume { get; set; }
    public string? ob_lpn_shipping_charge { get; set; }
    public string? ob_lpn_type { get; set; }
    public string? ob_lpn_asset_nbr { get; set; }
    public string? ob_lpn_asset_seal_nbr { get; set; }
    public string? serial_nbr { get; set; }
    public string? customer_po_type { get; set; }
    public string? customer_vendor_code { get; set; }
    public string? order_hdr_cust_date_1 { get; set; }
    public string? order_hdr_cust_date_2 { get; set; }
    public string? order_hdr_cust_date_3 { get; set; }
    public string? order_hdr_cust_date_4 { get; set; }
    public string? order_hdr_cust_date_5 { get; set; }
    public string? order_hdr_cust_number_1 { get; set; }
    public string? order_hdr_cust_number_2 { get; set; }
    public string? order_hdr_cust_number_3 { get; set; }
    public string? order_hdr_cust_number_4 { get; set; }
    public string? order_hdr_cust_number_5 { get; set; }
    public string? order_hdr_cust_decimal_1 { get; set; }
    public string? order_hdr_cust_decimal_2 { get; set; }
    public string? order_hdr_cust_decimal_3 { get; set; }
    public string? order_hdr_cust_decimal_4 { get; set; }
    public string? order_hdr_cust_decimal_5 { get; set; }
    public string? order_hdr_cust_short_text_1 { get; set; }
    public string? order_hdr_cust_short_text_2 { get; set; }
    public string? order_hdr_cust_short_text_3 { get; set; }
    public string? order_hdr_cust_short_text_4 { get; set; }
    public string? order_hdr_cust_short_text_5 { get; set; }
    public string? order_hdr_cust_short_text_6 { get; set; }
    public string? order_hdr_cust_short_text_7 { get; set; }
    public string? order_hdr_cust_short_text_8 { get; set; }
    public string? order_hdr_cust_short_text_9 { get; set; }
    public string? order_hdr_cust_short_text_10 { get; set; }
    public string? order_hdr_cust_short_text_11 { get; set; }
    public string? order_hdr_cust_short_text_12 { get; set; }
    public string? order_hdr_cust_long_text_1 { get; set; }
    public string? order_hdr_cust_long_text_2 { get; set; }
    public string? order_hdr_cust_long_text_3 { get; set; }
    public string? order_dtl_cust_date_1 { get; set; }
    public string? order_dtl_cust_date_2 { get; set; }
    public string? order_dtl_cust_date_3 { get; set; }
    public string? order_dtl_cust_date_4 { get; set; }
    public string? order_dtl_cust_date_5 { get; set; }
    public string? order_dtl_cust_number_1 { get; set; }
    public string? order_dtl_cust_number_2 { get; set; }
    public string? order_dtl_cust_number_3 { get; set; }
    public string? order_dtl_cust_number_4 { get; set; }
    public string? order_dtl_cust_number_5 { get; set; }
    public string? order_dtl_cust_decimal_1 { get; set; }
    public string? order_dtl_cust_decimal_2 { get; set; }
    public string? order_dtl_cust_decimal_3 { get; set; }
    public string? order_dtl_cust_decimal_4 { get; set; }
    public string? order_dtl_cust_decimal_5 { get; set; }
    public string? order_dtl_cust_short_text_1 { get; set; }
    public string? order_dtl_cust_short_text_2 { get; set; }
    public string? order_dtl_cust_short_text_3 { get; set; }
    public string? order_dtl_cust_short_text_4 { get; set; }
    public string? order_dtl_cust_short_text_5 { get; set; }
    public string? order_dtl_cust_short_text_6 { get; set; }
    public string? order_dtl_cust_short_text_7 { get; set; }
    public string? order_dtl_cust_short_text_8 { get; set; }
    public string? order_dtl_cust_short_text_9 { get; set; }
    public string? order_dtl_cust_short_text_10 { get; set; }
    public string? order_dtl_cust_short_text_11 { get; set; }
    public string? order_dtl_cust_short_text_12 { get; set; }
    public string? order_dtl_cust_long_text_1 { get; set; }
    public string? order_dtl_cust_long_text_2 { get; set; }
    public string? order_dtl_cust_long_text_3 { get; set; }
    public string? invn_attr_d { get; set; }
    public string? invn_attr_e { get; set; }
    public string? invn_attr_f { get; set; }
    public string? invn_attr_g { get; set; }
    public string? order_type { get; set; }
    public string? rcvd_trailer_nbr { get; set; }
    public string? stop_seal_nbr { get; set; }
    public string? ship_request_line { get; set; }
}
